### ISSUE TITLE
paypal issue

### ISSUE THREAD

**Issue by desbo** [guardian/contributions-frontend#265]
We should try to reproduce this. could be connected to the phony `complete` events

> I have attempted to make a one-off donation via PayPal, without success.
> From the page "Support the Guardian's quality journalism .............make
> a one-off...........today", the "processing" run symbol appears, but does
> not appear able to connect to PayPal.

> I tried to make the PayPal contribution on PC running Windows 7 Home
> Edition SP 1, via IE 11, version: 11.0.9600.18665. For the record, since I
> have been a PayPal participant (several years now), I have had only one
> other rejection.
>

**Comment by jranks123** [comment]
Did a little investigation, the proportion of our payments from PayPal has been steady at 60%-65% for the past few months. This doesn't mean there isn't a problem but hopefully means if there is one, it isn't affecting Paypal payments in a large way. 

<img width="719" alt="screenshot at may 16 21-12-02" src="https://cloud.githubusercontent.com/assets/2844554/26126157/7fb9e94c-3a7c-11e7-8c09-01366f191390.png">
