### ISSUE TITLE
Contributions IE11 Paypal payment not possible

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/contributions-frontend#380]
A user has reported that when he tried to make a contribution using paypal in IE11, the paypal window never opens. He just gets an in progress indicator that hangs there.

I've reproduced this on CODE.
Debugger on IE and system logs indicate that the initial auth toke request is sent to Paypal
and Paypal auth token is successfully received, however no payment attempt takes place, but nothing happens after that.

For Reference: IE11 is the sixth most popular browser according to Google Analytics:
It has 23,436,314 unique views in the past month - making up 4.36% of all unique page views.

**Comment by joelochlann** [comment]
Fixed by #384
