### ISSUE TITLE
IE11 - No indication in browser that Stripe payment is successful

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/contributions-frontend#381]
Issue found on CODE platform.
In IE11, when I try to pay with Stripe, there is no indication that the payment was successful. The stripe window closes, but there is nothing to show whether the payment succeeded or not. The user will receive a thank-you email, but there should also be an indication in the browser to guard against the user thinking it hasnt worked and attempting it again.
On other browsers you are taken through to the thank you page at this point.

Note: IE 11 still has significant usage so this will impact many users:
![image](https://user-images.githubusercontent.com/7239344/34154094-43f133f4-e4ac-11e7-8557-548bb1ea3e27.png)

**Comment by joelochlann** [comment]
Fixed by #384
